version: '3.6'
services:
  nginx:
    container_name: my-nginx 
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./myhtml:/var/www/myhtml
      - ./ssl:/etc/nginx/certs
